// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDREFFtlp9h7Kf6vU746MzRohv17VrEdw',
    appId: '1:335423965361:web:237fb45767e0eaf33a3a90',
    messagingSenderId: '335423965361',
    projectId: 'ostello-62181',
    authDomain: 'ostello-62181.firebaseapp.com',
    storageBucket: 'ostello-62181.appspot.com',
    measurementId: 'G-RRTXMDHHMP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTSwBdT0ZTy86blYs98gzATiaLscizsr4',
    appId: '1:335423965361:ios:03d635da8bb96c323a3a90',
    messagingSenderId: '335423965361',
    projectId: 'ostello-62181',
    storageBucket: 'ostello-62181.appspot.com',
    iosBundleId: 'com.example.adminLogin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTSwBdT0ZTy86blYs98gzATiaLscizsr4',
    appId: '1:335423965361:ios:03d635da8bb96c323a3a90',
    messagingSenderId: '335423965361',
    projectId: 'ostello-62181',
    storageBucket: 'ostello-62181.appspot.com',
    iosBundleId: 'com.example.adminLogin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLzI2BruEg_DUiGnsMSkFIU59xksWoWHY',
    appId: '1:335423965361:android:bc089f292573277b3a3a90',
    messagingSenderId: '335423965361',
    projectId: 'ostello-62181',
    storageBucket: 'ostello-62181.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDREFFtlp9h7Kf6vU746MzRohv17VrEdw',
    appId: '1:335423965361:web:6b7a0e1c97353f903a3a90',
    messagingSenderId: '335423965361',
    projectId: 'ostello-62181',
    authDomain: 'ostello-62181.firebaseapp.com',
    storageBucket: 'ostello-62181.appspot.com',
    measurementId: 'G-R563HJMTBV',
  );

}