// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIQaEQEGpKTM2qxksfJzrSJrtzrtm2Qg',
    appId: '1:706591245596:web:6d5dc7d43c8b69e28766d9',
    messagingSenderId: '706591245596',
    projectId: 'hostel-416ec',
    authDomain: 'hostel-416ec.firebaseapp.com',
    storageBucket: 'hostel-416ec.appspot.com',
    measurementId: 'G-EGNNKSYXR6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlN6Uv-0ZxC_1LFFTRsW03XGEnRHER2oM',
    appId: '1:706591245596:ios:2f413b746bd61b168766d9',
    messagingSenderId: '706591245596',
    projectId: 'hostel-416ec',
    storageBucket: 'hostel-416ec.appspot.com',
    iosBundleId: 'com.example.cs',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlN6Uv-0ZxC_1LFFTRsW03XGEnRHER2oM',
    appId: '1:706591245596:ios:2f413b746bd61b168766d9',
    messagingSenderId: '706591245596',
    projectId: 'hostel-416ec',
    storageBucket: 'hostel-416ec.appspot.com',
    iosBundleId: 'com.example.cs',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpmbOiet6EEmZ_TexFd9bBXHhoiNb_qH8',
    appId: '1:706591245596:android:28fd8ab0a286bc948766d9',
    messagingSenderId: '706591245596',
    projectId: 'hostel-416ec',
    storageBucket: 'hostel-416ec.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmNe0NZabU8QGIo58yj-Ar7Sn5VdSCxLg',
    appId: '1:706591245596:web:9d1c364d743d98ea8766d9',
    messagingSenderId: '706591245596',
    projectId: 'hostel-416ec',
    authDomain: 'hostel-416ec.firebaseapp.com',
    storageBucket: 'hostel-416ec.appspot.com',
    measurementId: 'G-XB4ZKEL0M7',
  );

}